server:
  port: 8900
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka,
        http://localhost:8762/eureka
spring:
  application:
    name: StockService
  zipkin:
    base-url: http://localhost:9411
sleuth:
  sampler:
    probability: 1

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    health:
#      show-details: always
